### ISSUE TITLE
Deadlocking Szymanski

### ISSUE THREAD

**Issue by weltoph** [ericpony/safety-prover#1]
Hey!

In the specification of [Szymanski's mutual exclusion algorithm](https://github.com/ericpony/safety-prover/blob/master/SafetyProver/benchmarks/Szymanski.txt) the state Q7 cannot be read by the `idle` blocks. Hence - as far as I understand - the system deadlocks as soon as someone enters Q7. I was wondering if this is intended behaviour.

**Comment by ericpony** [comment]
Hi, thanks a lot for the report. You are right - the model gets stuck after someone enters Q7, and hence is trivially safe. I have tried to fix the bug. The checker takes roughly the same time to verify the corrected version on my laptop (2.2 sec  vs 2.7 sec).

**Comment by ericpony** [comment]
Hi, thanks a lot for the report. You are right - the model gets stuck after someone enters Q7 and thus is trivially safe. I have tried to fix the bug. On my laptop, the checker takes slightly more time to verify the corrected version (increasing from 2.2 sec to 2.7 sec).
