### ISSUE TITLE
Resource allocater

### ISSUE THREAD

**Issue by weltoph** [ericpony/safety-prover#2]
Hey!

In the specification of the [resource allocator](https://github.com/ericpony/safety-prover/blob/2a7c61f99b604777519d5e5d386339f98409486f/SafetyProver/benchmarks/resource-allocator.txt#L24) there are two transitions to check if the resource allocator is in state r (where it, actually, can never move into) while it is not possible for the allocator to be in state c when a process wants to move from idle to request (although this should be possible if I understand the concept correctly).

**Comment by ericpony** [comment]
Hi, thank you very much for the report. The bug is fixed - it takes 89ms to verify the corrected version on my laptop. Please let me know if you find any further problems.
